branch-defaults:
  main:
    environment: node-express-env
    group_suffix: null
global:
  application_name: trekr-back
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
